# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: rae_dux_left
  - board: nice_nano_v2
    shield: rae_dux_right
  - board: nice_nano_v2
    shield: berylline_left
  - board: nice_nano_v2
    shield: berylline_right
  - board: seeeduino_xiao_ble
    shield: hummingbird
  - board: nice_nano_v2
    shield: wizzades_left
  - board: nice_nano_v2
    shield: wizzades_right
  - board: nice_nano_v2
    shield: chocofi_left
  - board: nice_nano_v2
    shield: chocofi_right
  - board: nice_nano_v2
    shield: hypergolic_left
  - board: nice_nano_v2
    shield: hypergolic_right
